# Generated by Django 6.0.3 on 2026-03-20 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='评估标题')),
                ('project_description', models.TextField(verbose_name='项目描述')),
                ('meeting_notes', models.TextField(blank=True, verbose_name='会议纪要')),
                ('overall_risk_level', models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], max_length=20, null=True, verbose_name='整体风险等级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('analyzing', '分析中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '风险评估',
                'verbose_name_plural': '风险评估',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', '技术风险'), ('schedule', '进度风险'), ('resource', '资源风险'), ('requirement', '需求风险'), ('communication', '沟通风险'), ('external', '外部风险')], max_length=20, verbose_name='风险类别')),
                ('title', models.CharField(max_length=200, verbose_name='风险标题')),
                ('description', models.TextField(verbose_name='风险描述')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], max_length=20, verbose_name='风险等级')),
                ('probability', models.IntegerField(default=5, help_text='1-10，发生概率', verbose_name='发生概率')),
                ('impact', models.IntegerField(default=5, help_text='1-10，影响程度', verbose_name='影响程度')),
                ('mitigation_suggestions', models.TextField(verbose_name='应对建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_items', to='risk_agent.riskassessment', verbose_name='风险评估')),
            ],
            options={
                'verbose_name': '风险项',
                'verbose_name_plural': '风险项',
                'ordering': ['risk_level'],
            },
        ),
    ]
