# Generated by Django 6.0.3 on 2026-03-20 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='对话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话',
                'verbose_name_plural': '对话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('sources', models.JSONField(blank=True, null=True, verbose_name='引用来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rag.conversation', verbose_name='对话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('chunk_index', models.IntegerField(default=0, verbose_name='分块索引')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='向量嵌入')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document', verbose_name='来源文档')),
            ],
            options={
                'verbose_name': '向量文档',
                'verbose_name_plural': '向量文档',
                'indexes': [models.Index(fields=['source_document'], name='rag_vectord_source__c14d28_idx')],
            },
        ),
    ]
